name: Projectile Motion Linting (MH)

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Python version

    - name: Install dependencies
      
      run:
        python -m pip install --upgrade pip
        python  pip install numpy  # Install numpy
        # pip install -r requirements.txt  
    - name: Install linter
      run:
        pip install pylint
    - name: List directory contents
      run: ls -al
    - name: lint projectile_motion_with_air_resistance.py
      run: pylint projectile_motion_with_air_resistance.py
